FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:ae09ecc3d754bc1726cbda3e2599cc7839e09fe1cc547ce173cf669b645be3cc

ARG HELM_VERSION=3.15.4
ARG TARGETARCH=amd64

RUN microdnf install -y ca-certificates gzip tar && microdnf clean all
RUN cd /tmp \
 && curl -fsSLO "https://get.helm.sh/helm-v${HELM_VERSION}-linux-${TARGETARCH}.tar.gz" \
 && curl -fsSLO "https://get.helm.sh/helm-v${HELM_VERSION}-linux-${TARGETARCH}.tar.gz.sha256sum" \
 && sha256sum -c "helm-v${HELM_VERSION}-linux-${TARGETARCH}.tar.gz.sha256sum" \
 && tar -xzf "helm-v${HELM_VERSION}-linux-${TARGETARCH}.tar.gz" \
 && install -m 0755 "linux-${TARGETARCH}/helm" /usr/local/bin/helm \
 && rm -rf "helm-v${HELM_VERSION}-linux-${TARGETARCH}.tar.gz" "helm-v${HELM_VERSION}-linux-${TARGETARCH}.tar.gz.sha256sum" "linux-${TARGETARCH}"

USER 1001
WORKDIR /tmp/work
ENTRYPOINT ["/usr/local/bin/helm"]
