FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

ARG HELM_VERSION=3.15.4
ARG TARGETARCH=amd64

RUN microdnf install -y ca-certificates curl gzip tar && microdnf clean all
RUN curl -fsSLo /tmp/helm.tar.gz "https://get.helm.sh/helm-v${HELM_VERSION}-linux-${TARGETARCH}.tar.gz" \
 && curl -fsSLo /tmp/helm.tar.gz.sha256sum "https://get.helm.sh/helm-v${HELM_VERSION}-linux-${TARGETARCH}.tar.gz.sha256sum" \
 && cd /tmp \
 && sha256sum -c helm.tar.gz.sha256sum \
 && tar -xzf helm.tar.gz \
 && install -m 0755 "linux-${TARGETARCH}/helm" /usr/local/bin/helm \
 && rm -rf /tmp/helm.tar.gz /tmp/helm.tar.gz.sha256sum "/tmp/linux-${TARGETARCH}"

USER 1001
WORKDIR /tmp/work
ENTRYPOINT ["/usr/local/bin/helm"]
